version: '3.9'
services:
  chatwithdoc-api:
    container_name: chatwithdoc-api
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: 'on-failure'
    ports:
      - 8002:8002
    env_file:
      - ./app/.env
    networks:
      backend-network:
        ipv4_address: 172.20.0.10
      monitoring-chatwithdoc:
        ipv4_address: 172.21.0.10

  prometheus:
    container_name: chatwithdoc-prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      monitoring-chatwithdoc:
        ipv4_address: 172.21.0.11

  grafana:
    container_name: chatwithdoc-grafana
    image: grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      monitoring-chatwithdoc:
        ipv4_address: 172.21.0.12

volumes:
  grafana_data:

networks:
  backend-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

  monitoring-chatwithdoc:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24